module.exports = {
  weatherData: [
    {
      day: 'tod',
      hour: 0,
      weather: 'clear-night',
      temp: 11,
      time: '00:00',
    },
    {
      day: 'tod',
      hour: 1,
      weather: 'partly-cloudy-night',
      temp: 10,
      time: '01:00',
    },
    { day: 'tod', hour: 2, weather: 'rainy', temp: 9, time: '02:00' },
    {
      day: 'tod',
      hour: 3,
      weather: 'cloudy',
      temp: 8,
      time: '03:00',
    },
    {
      day: 'tod',
      hour: 4,
      weather: 'partly-cloudy-night',
      temp: 7,
      time: '04:00',
    },
    {
      day: 'tod',
      hour: 5,
      weather: 'clear-night',
      temp: 7,
      time: '05:00',
    },
    {
      day: 'tod',
      hour: 6,
      weather: 'sunny',
      temp: 12,
      time: '06:00',
    },
    {
      day: 'tod',
      hour: 7,
      weather: 'sunny',
      temp: 12,
      time: '07:00',
    },
    {
      day: 'tod',
      hour: 8,
      weather: 'sunny',
      temp: 13,
      time: '08:00',
    },
    {
      day: 'tod',
      hour: 9,
      weather: 'partly-cloudy',
      temp: 14,
      time: '09:00',
    },
    {
      day: 'tod',
      hour: 10,
      weather: 'cloudy',
      temp: 16,
      time: '10:00',
    },
    {
      day: 'tod',
      hour: 11,
      weather: 'rainy',
      temp: 17,
      time: '11:00',
    },
    {
      day: 'tod',
      hour: 12,
      weather: 'rainy',
      temp: 19,
      time: '12:00',
    },
    {
      day: 'tod',
      hour: 13,
      weather: 'rainy',
      temp: 20,
      time: '13:00',
    },
    {
      day: 'tod',
      hour: 14,
      weather: 'partly-cloudy',
      temp: 20,
      time: '14:00',
    },
    {
      day: 'tod',
      hour: 15,
      weather: 'partly-cloudy',
      temp: 20,
      time: '15:00',
    },
    {
      day: 'tod',
      hour: 16,
      weather: 'partly-cloudy',
      temp: 19,
      time: '16:00',
    },
    {
      day: 'tod',
      hour: 17,
      weather: 'cloudy',
      temp: 20,
      time: '17:00',
    },
    {
      day: 'tod',
      hour: 18,
      weather: 'cloudy',
      temp: 19,
      time: '18:00',
    },
    {
      day: 'tod',
      hour: 19,
      weather: 'cloudy',
      temp: 18,
      time: '19:00',
    },
    {
      day: 'tod',
      hour: 20,
      weather: 'rainy',
      temp: 17,
      time: '20:00',
    },
    {
      day: 'tod',
      hour: 21,
      weather: 'rainy',
      temp: 15,
      time: '21:00',
    },
    {
      day: 'tod',
      hour: 22,
      weather: 'rainy',
      temp: 12,
      time: '22:00',
    },
    {
      day: 'tod',
      hour: 23,
      weather: 'rainy',
      temp: 10,
      time: '23:00',
    },

    {
      day: 'tom',
      hour: 0,
      weather: 'thunderstorm',
      temp: 8,
      time: '00:00',
    },
    {
      day: 'tom',
      hour: 1,
      weather: 'thunderstorm',
      temp: 6,
      time: '01:00',
    },
    {
      day: 'tom',
      hour: 2,
      weather: 'thunderstorm',
      temp: 4,
      time: '02:00',
    },
    {
      day: 'tom',
      hour: 3,
      weather: 'thunderstorm',
      temp: 3,
      time: '03:00',
    },
    {
      day: 'tom',
      hour: 4,
      weather: 'thunderstorm',
      temp: 2,
      time: '04:00',
    },
    {
      day: 'tom',
      hour: 5,
      weather: 'cloudy',
      temp: 2,
      time: '05:00',
    },
    {
      day: 'tom',
      hour: 6,
      weather: 'cloudy',
      temp: 0,
      time: '06:00',
    },
    {
      day: 'tom',
      hour: 7,
      weather: 'cloudy',
      temp: -1,
      time: '07:00',
    },
    {
      day: 'tom',
      hour: 8,
      weather: 'partly-cloudy',
      temp: -1,
      time: '08:00',
    },
    {
      day: 'tom',
      hour: 9,
      weather: 'partly-cloudy',
      temp: -1,
      time: '09:00',
    },
    {
      day: 'tom',
      hour: 10,
      weather: 'snowy',
      temp: 0,
      time: '10:00',
    },
    {
      day: 'tom',
      hour: 11,
      weather: 'snowy',
      temp: 1,
      time: '11:00',
    },
    {
      day: 'tom',
      hour: 12,
      weather: 'snowy',
      temp: 1,
      time: '12:00',
    },
    {
      day: 'tom',
      hour: 13,
      weather: 'partly-cloudy',
      temp: 3,
      time: '13:00',
    },
    {
      day: 'tom',
      hour: 14,
      weather: 'partly-cloudy',
      temp: 5,
      time: '14:00',
    },
    {
      day: 'tom',
      hour: 15,
      weather: 'cloudy',
      temp: 7,
      time: '15:00',
    },
    {
      day: 'tom',
      hour: 16,
      weather: 'cloudy',
      temp: 9,
      time: '16:00',
    },
    {
      day: 'tom',
      hour: 17,
      weather: 'rainy',
      temp: 9,
      time: '17:00',
    },
    {
      day: 'tom',
      hour: 18,
      weather: 'rainy',
      temp: 10,
      time: '18:00',
    },
    {
      day: 'tom',
      hour: 19,
      weather: 'cloudy',
      temp: 10,
      time: '19:00',
    },
    {
      day: 'tom',
      hour: 20,
      weather: 'cloudy',
      temp: 9,
      time: '20:00',
    },
    {
      day: 'tom',
      hour: 21,
      weather: 'rainy',
      temp: 8,
      time: '21:00',
    },
    {
      day: 'tom',
      hour: 22,
      weather: 'rainy',
      temp: 7,
      time: '22:00',
    },
    {
      day: 'tom',
      hour: 23,
      weather: 'rainy',
      temp: 5,
      time: '23:00',
    },
    { day: 'tom', hour: 0, weather: 'rainy', temp: 3, time: '00:00' },
  ],
  locationData: [
    {
      name: '北京',
      id: '101010100',
      lat: '39.90499',
      lon: '116.40529',
      adm2: '北京',
      adm1: '北京市',
      country: '中国',
      tz: 'Asia/Shanghai',
      utcOffset: '+08:00',
      isDst: '0',
      type: 'city',
      rank: '10',
      fxLink: 'https://www.qweather.com/weather/beijing-101010100.html',
    },
  ],
};
